[package]
name = "rusty-laby"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.133"
byteorder = "1.5.0"
rand = "0.9.0-beta.1"
piston_window = "0.132.0"

[[bin]]
name="server"
path="src/server.rs"

[[bin]]
name="client"
path="src/main.rs"
